version: "3.9"
services:
  db:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/web:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
