# Generated by Django 4.0.4 on 2022-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zutat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgUrl', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='zutat',
            old_name='einheit',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='zutat',
            name='recipes',
            field=models.ManyToManyField(to='main.rezept'),
        ),
    ]
